### ISSUE TITLE
description wird als tinymce behandelt

### ISSUE THREAD

**Issue by Xendiadyon** [ErdmannFreunde/contao-news-meta#1]
Hallo,

wir haben gerade das Problem, dass das description-Feld per TinyMCE verwaltet wird (Contao 4.4.28).
Dadurch wird immer automatisch ein p-Tag eingefügt, welches natürlich in der meta description nichts zu suchen hat.

Gibt es eine Möglichkeit, die Verwendung von TinyMCE für dieses Textfeld zu verbieten?

![image](https://user-images.githubusercontent.com/2657385/49233905-47179680-f3f7-11e8-93f1-8bff9f684773.png)

Vielen Dank

**Comment by Xendiadyon** [comment]
Macht es überhaupt Sinn, dies als textarea zu definieren? Text wäre doch sinnvoller, da sowieso keine Zeilenumbrüche verwendet werden dürfen, richtig?

**Comment by denniserdmann** [comment]
Wir orientieren uns hier ab dem Contao Standard, d.h. auch in der Seitenstruktur wird für die Description eine Textarea verwendet.

Ich wundere mich allerdings, dass bei euch das Feld als  tinyMCE dargestellt wird. Habt ihr eine zusätzliche tinyMCE Erweiterung im Einsatz? (das würde den kleinen Zusatz „Powered by TinyMCE“ an der unteren, rechten Ecke erklären) Und wenn ja, macht diese Erweiterung bei der Description in der Seitenstruktur eine Ausnahme?

Ich würde zunächst den Fehler im tinyMCE (bzw. der Erweiterung suchen). 
Zum Vergleich: So sieht es eigentlich aus (ist allerdings eine 4.5.14)

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/3773697/49236401-51885f00-f3fc-11e8-823c-47daf519a876.png">
